[package]
name = "fly-into-the-maelstrom"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
serde_with = "3.9.0"

[[bin]]
name = "echo"
path = "src/bin/echo.rs"
